CREATE PRODUCT (
	Product_id NUMBER,
	Product_Name VARCHAR2(20) CONSTRAINT NN_PRODUCT NOT NULL,
	Price NUMBER CONSTRAINT PN_CUSTOMER CHECK (Price>0),
CONSTRAINT PK_PRODUCT PRIMARY KEY (Product_id)
);

CREATE CUSTOMER (
	Customer_id VARCHAR2(20),
	Customer_Name VARCHAR2(20) CONSTRAINT NN_CUSTOMER NOT NULL,
	Customer_Tel NUMBER,
             CONSTRAINT PK_CUSTOMER PRIMARY KEY (Customer_id)
            

);
CREATE ORDERS (
	Customer_id VARCHAR2(20),
Product_id VARCHAR2(20),
Quantity NUMBER,
Total_amount NUMBER,
CONSTRAINT FK_ORDERS FOREIGN KEY (Customer_id)
 REFERENCES CUSTOMER (Customer_id),
CONSTRAINT FK_ORDERS FOREIGN KEY (Product_id)
 REFERENCES PRODUCT (Product_id),

);
ALTER TABLE PRODUCT ADD Category (VARCHAR2(20));
ALTER TABLE ORDERS ADD OrderDate (DATE) DEFAULT SYSDATE;

